version: "3.9"

services:
  ganache:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"
    command:
      - "--accounts"
      - "10"
      - "--defaultBalanceEther"
      - "1000"
      - "--host"
      - "0.0.0.0"

  streamlit:
    build: .
    depends_on:
      - ganache
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_WATCH_USE_POLLING=false
      - GANACHE_URL=http://ganache:8545
    volumes:
      - .:/app
